[2021-12-10 13:13:35,231] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: core_concepts.python_function 2021-12-10T18:12:01.224403+00:00 [queued]>
[2021-12-10 13:13:35,236] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: core_concepts.python_function 2021-12-10T18:12:01.224403+00:00 [queued]>
[2021-12-10 13:13:35,236] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2021-12-10 13:13:35,236] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2021-12-10 13:13:35,236] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2021-12-10 13:13:35,240] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): python_function> on 2021-12-10T18:12:01.224403+00:00
[2021-12-10 13:13:35,246] {standard_task_runner.py:53} INFO - Started process 2641 to run task
[2021-12-10 13:13:35,280] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: core_concepts.python_function 2021-12-10T18:12:01.224403+00:00 [running]> 220.1.168.192.in-addr.arpa
[2021-12-10 13:13:35,291] {taskinstance.py:1145} ERROR - print_random_number() missing 1 required positional argument: 'number'
Traceback (most recent call last):
  File "/Users/manassikri/opt/miniconda3/envs/airflowtutorial/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/Users/manassikri/opt/miniconda3/envs/airflowtutorial/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/Users/manassikri/opt/miniconda3/envs/airflowtutorial/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: print_random_number() missing 1 required positional argument: 'number'
[2021-12-10 13:13:35,292] {taskinstance.py:1202} INFO - Marking task as FAILED.dag_id=core_concepts, task_id=python_function, execution_date=20211210T181201, start_date=20211210T181335, end_date=20211210T181335
[2021-12-10 13:13:45,215] {logging_mixin.py:112} INFO - [2021-12-10 13:13:45,213] {local_task_job.py:103} INFO - Task exited with return code 1
